// maps from item text: 'Item Class: ...'
const itemClassToPobType = {
	'Rings': 'Ring',
	'Quivers': 'Quiver',
	'Boots': 'Boots',
	'Amulets': 'Amulet',
	'Body Armours': 'Body Armour',
	'Helmets': 'Helmet',
	'Gloves': 'Gloves',
	'Belts': 'Belt',
	'Shields': 'Shield',
	'Foci': 'Focus',
	'Bucklers': 'Buckler',
	'Bows': 'Bow',
	'Crossbows': 'Crossbows',
	'Claws': 'Claw',
	'Spears': 'Spear',
	'Flails': 'Flail',
	'Staves': 'Staff',
	'Warstaves': 'Staff',
	'One Hand Maces': 'One Handed Mace',
	'One Hand Swords': 'One Handed Sword',
	'Sceptres': 'Sceptre',
	'Thrusting One Hand Swords': 'Thrusting One Handed Sword',
	'Wands': 'Wand',
	'Two Hand Axes': 'Two Handed Axe',
	'Two Hand Swords': 'Two Handed Sword',
	'Two Hand Maces': 'Two Handed Mace',
	'Daggers': 'Dagger',
	'Rune Daggers': 'Dagger',
	'One Hand Axes': 'One Handed Axe',
	'Utility Flasks': 'Flask',
};

module.exports = {slots, itemClassToPobType};
