// From PoB src/Classes/ItemsTab.lua
// maps trade api types to pob equipment slot
const slots = {
	'weapon': 'Weapon 1',
	'weapon.one': 'Weapon 1',
	'weapon.onemelee': 'Weapon 1',
	'weapon.twomelee': 'Weapon 1',
	'weapon.bow': 'Weapon 1',
	'weapon.claw': 'Weapon 1',
	'weapon.dagger': 'Weapon 1',
	'weapon.basedagger': 'Weapon 1',
	'weapon.runedagger': 'Weapon 1',
	'weapon.oneaxe': 'Weapon 1',
	'weapon.onesword': 'Weapon 1',
	'weapon.onemace': 'Weapon 1',
	'weapon.basemace': 'Weapon 1',
	'weapon.sceptre': 'Weapon 1',
	'weapon.staff': 'Weapon 1',
	'weapon.basestaff': 'Weapon 1',
	'weapon.warstaff': 'Weapon 1',
	'weapon.twoaxe': 'Weapon 1',
	'weapon.twomace': 'Weapon 1',
	'weapon.twosword': 'Weapon 1',
	'weapon.wand': 'Weapon 1',
	'weapon.rod': 'Weapon 1',
	'accessory.amulet': 'Amulet',
	'armour.helmet': 'Helmet',
	'armour.shield': 'Weapon 2',
	'armour.quiver': 'Weapon 2',
	'armour.chest': 'Body Armour',
	'armour.gloves': 'Gloves',
	'armour.boots': 'Boots',
	'accessory.ring': 'Ring 1',
	'accessory.belt': 'Belt',
	'jewel': 'Jewel Any',
	'jewel.base': 'Jewel Base',
	'jewel.abyss': 'Jewel Abyss',
};

// maps from item text: 'Item Class: ...'
const itemClassToPobType = {
	'Rings': 'Ring',
	'Quivers': 'Quiver',
	'Boots': 'Boots',
	'Amulets': 'Amulet',
	'Body Armours': 'Body Armour',
	'Helmets': 'Helmet',
	'Gloves': 'Gloves',
	'Belts': 'Belt',
	'Shields': 'Shield',
	'Bows': 'Bow',
	'Claws': 'Claw',
	'Staves': 'Staff',
	'Warstaves': 'Staff',
	'One Hand Maces': 'One Handed Mace',
	'One Hand Swords': 'One Handed Sword',
	'Sceptres': 'Sceptre',
	'Thrusting One Hand Swords': 'Thrusting One Handed Sword',
	'Wands': 'Wand',
	'Two Hand Axes': 'Two Handed Axe',
	'Two Hand Swords': 'Two Handed Sword',
	'Two Hand Maces': 'Two Handed Mace',
	'Daggers': 'Dagger',
	'Rune Daggers': 'Dagger',
	'One Hand Axes': 'One Handed Axe',
	'Utility Flasks': 'Flask',
};

// map trade api type to pob crafting type
// const craftTypes = {
// 	'weapon': 'One Handed Axe',
// 	'weapon.one': 'One Handed Axe',
// 	'weapon.onemelee': 'One Handed Axe',
// 	'weapon.twomelee': 'Two Handed Axe',
// 	'weapon.bow': 'Bow',
// 	'weapon.claw': 'Claw',
// 	'weapon.dagger': 'Dagger',
// 	'weapon.basedagger': 'Dagger',
// 	'weapon.runedagger': 'Dagger',
// 	'weapon.oneaxe': 'One Handed Axe',
// 	'weapon.onesword': 'One Handed Sword',
// 	'weapon.onemace': 'One Handed Mace',
// 	'weapon.basemace': 'One Handed Mace',
// 	'weapon.sceptre': 'Sceptre',
// 	'weapon.staff': 'Staff',
// 	'weapon.basestaff': 'Staff',
// 	'weapon.warstaff': 'Staff',
// 	'weapon.twoaxe': 'Two Handed Axe',
// 	'weapon.twomace': 'Two Handed Mace',
// 	'weapon.twosword': 'Two Handed Sword',
// 	'weapon.wand': 'Wand',
// 	'weapon.rod': 'One Handed Axe',
// 	'accessory.amulet': 'Amulet',
// 	'armour.helmet': 'Helmet',
// 	'armour.shield': 'Shield',
// 	'armour.quiver': 'Quiver',
// 	'armour.chest': 'Body Armour',
// 	'armour.gloves': 'Gloves',
// 	'armour.boots': 'Boots',
// 	'accessory.ring': 'Ring',
// 	'accessory.belt': 'Belt',
// 	'jewel': 'not craftable',
// 	'jewel.base': 'not craftable',
// 	'jewel.abyss': 'not craftable',
// };

module.exports = {slots, itemClassToPobType};
