name: Build and Draft Release on Git Push

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build_electron:
    name: Compile and Draft Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            args: --win
          - os: ubuntu-latest
            args: --linux

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Read version from package.json
        id: package_version
        shell: bash
        run: echo "prop_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Compile Electron Binaries
        run: npx electron-builder ${{ matrix.args }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          name: "v${{ steps.package_version.outputs.prop_version }}"
          tag_name: "v${{ steps.package_version.outputs.prop_version }}"
          body: |
            Automated build for version ${{ steps.package_version.outputs.prop_version }}
            Generated from commit ${{ github.sha }}
        files: |
            dist/arevtur-*.exe
            dist/arevtur-*.exe.blockmap
            dist/latest.yml
            dist/arevtur-*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
